### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by shenqihui** [douglasduteil/karma-json-reporter#9]
```
ERROR [karma]: [ReferenceError: log is not defined]
ReferenceError: log is not defined
    at /home/vagrant/github/karma_test/node_modules/karma-json-reporter/index.js:38:11
    at /home/vagrant/github/karma_test/node_modules/karma/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:108:15)
```

here: https://github.com/douglasduteil/karma-json-reporter/blob/master/index.js#L38

Is there some package i haven't required?

**Comment by SlavikCA** [comment]
Issue fixed in this commit:
https://github.com/douglasduteil/karma-json-reporter/commit/c25ec540701907336e1eae13a16390cd35c55301

Just use version 1.2.

I know, this is old issue. 
I'm writing that, because Readme.md  still points to 1.1, where this issue still exists. Needs to be updated to point to 1.2.
